[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.9" }
tokio = { version = "1.17.0", features = ["full"] }
select = "0.5.0"
url = "2.2.2"
serde_json = "1.0.79"
futures = "0.3.21"
crossbeam-channel = "0.5.4"
governor = "0.4.2"